- package: github.com/golang/protobuf
  repo: https://github.com/golang/protobuf.git
  vcs: git
  branch: master 
  subpackages:
  - ptypes
  - ptypes/any
  - proto 
  - protoc-gen-go
- package: github.com/lestrrat/go-file-rotatelogs
  version: master
- package: github.com/hashicorp/errwrap
- package: github.com/davecgh/go-spew
  version: v1.1.0